name: Xcode build iOS 18

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-15

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode_16.1.app

      - name: Xcode version
        run: /usr/bin/xcodebuild -version

      - name: Xcode iOS build
        run: |
          cd Xcode/
          xcodebuild clean build -scheme TheNews -destination 'platform=iOS Simulator,name=iPhone 16,OS=18.1'
